---
- name: Install webhook-server
  ansible.builtin.include_role:
    name: download-install-binary
  tags: setup

- name: Create webhook user
  ansible.builtin.include_role:
    name: create-os-user
  vars:
    groups_to_create: "{{ webhook_group }}"
    users: "{{ webhook_user }}"
