---
- name: Send notification to MS Teams
  ansible.builtin.include_tasks: send-to-msteams.yaml
  when: send_to_msteams|bool

- name: Send notification to Elasticsearch
  ansible.builtin.include_tasks: send-to-elastic.yaml
  when: send_to_elastic|bool

- name: Install webhook-server
  ansible.builtin.include_tasks: install-webhook-server.yaml
  when: install_webhook_server|bool

- name: Send notification to Homerun
  ansible.builtin.include_tasks: send-to-homerun.yaml
  when: send_to_homerun|bool
